<div class="page-heading"><div><span class="eyebrow">THE BIG PICTURE</span><h1>Your workspace, at a glance.</h1><p>Everything you need to build a better learning experience.</p></div><a class="btn btn-primary" data-nav href="{{ route('admin.quizzes.create') }}"><x-icon name="plus"/> Create a quiz</a></div>
<section class="hero-banner"><div><span class="eyebrow light">GOOD LEARNING STARTS HERE</span><h2>Make every question count.</h2><p>Bring your subjects, questions, and people together.<br>Your next great assessment starts with one good question.</p><a class="btn btn-white" data-nav href="{{ route('admin.questions.create') }}">Add a question <x-icon name="arrow"/></a></div><div class="hero-art" aria-hidden="true"><div class="art-card card-back"></div><div class="art-card card-front"><span>YOUR NEXT QUIZ</span><strong>Think.<br>Learn.<br>Grow.</strong><i></i><i></i><i></i></div><span class="art-spark">+</span></div></section>
<x-stats :stats="$stats"/>
<div class="two-columns">
    <section class="panel"><div class="panel-heading"><div><h2>Your subjects</h2><p>A place for every area of knowledge.</p></div><a data-nav href="{{ route('admin.categories.index') }}" class="text-link">Manage <x-icon name="arrow"/></a></div>
    @forelse($categories as $category)<div class="subject-row"><span class="subject-icon" style="--subject:{{ $category->color }}">{{ mb_strtoupper(mb_substr($category->name,0,2)) }}</span><div><strong>{{ $category->name }}</strong><small>{{ $category->questions_count }} questions in your bank</small></div><a class="icon-link" aria-label="View {{ $category->name }} questions" data-nav href="{{ route('admin.questions.index',['category_id'=>$category->id]) }}"><x-icon name="arrow"/></a></div>@empty<x-empty title="Create your first subject" text="Categories help your learners find their next challenge."/>@endforelse
    </section>
    <section class="panel"><div class="panel-heading"><div><h2>A thoughtful starting point</h2><p>Build an assessment in three simple steps.</p></div></div><div class="step-list"><div><span>01</span><div><h3>Give ideas a home.</h3><p>Create categories for programming, sciences, languages, or any subject.</p></div></div><div><span>02</span><div><h3>Ask a good question.</h3><p>Add four answer choices, a correct answer, and a helpful explanation.</p></div></div><div><span>03</span><div><h3>Let learning happen.</h3><p>Set the time, choose who can participate, and publish your quiz.</p></div></div></div><div class="panel-callout"><x-icon name="palette"/><p>A different look for every learner. Explore themes in <a href="{{ route('admin.themes.index') }}" data-nav>Appearance</a>.</p></div></section>
</div>
<section class="panel section-gap"><div class="panel-heading"><div><h2>Recent activity</h2><p>The latest attempts across your workspace.</p></div><a class="text-link" data-nav href="{{ route('admin.reports.index') }}">All reports <x-icon name="arrow"/></a></div>@include('attempts.table',['attempts'=>$recent,'showUser'=>true])</section>
