<div class="page-heading"><div><span class="eyebrow">{{ $attempt->category_name }}</span><h1>{{ $attempt->quiz_title }}</h1><p>Take a breath. Read carefully. Choose your best answer.</p></div><div class="timer"><x-icon name="clock"/><div><small>Time remaining</small><strong data-countdown data-deadline="{{ $attempt->expires_at->toIso8601String() }}" data-server-now="{{ now()->toIso8601String() }}" data-expire-url="{{ route('attempts.show',$attempt) }}">--:--</strong></div></div></div>
@if($readOnly)<div class="notice">Administrator preview: you can inspect progress, but cannot answer for this learner.</div>@endif
<div class="attempt-layout"><section class="panel question-panel"><div class="question-topline"><span class="soft-badge">Question {{ $position }} / {{ $attempt->total_questions }}</span><span class="muted">Single correct answer &middot; 1 mark</span></div><h2 class="question-prompt">{{ $item->prompt }}</h2>
<form method="post" action="{{ route('attempts.answer',[$attempt,'question'=>$item->id]) }}" data-ajax data-autosave data-quiet>
    @csrf @method('PATCH')<x-errors/>
    <fieldset class="answer-list" @disabled($readOnly)><legend class="visually-hidden">Select your answer</legend>
    @foreach($item->options as $choice)@php $key=$choice['key']; $option=$choice['text']; @endphp<label class="answer-option"><input type="radio" name="selected_option" value="{{ $key }}" @checked($item->selected_option===$key)><span class="answer-letter">{{ chr(65+$loop->index) }}</span><span>{{ $option }}</span></label>@endforeach
    <label class="clear-answer"><input type="radio" name="selected_option" value="" @checked($item->selected_option===null)> Leave this question unanswered</label></fieldset>
    <div class="answer-save-row"><span data-save-state class="save-state" aria-live="polite">{{ $item->selected_option !== null ? 'Your answer is saved.' : 'Choose an answer to save it automatically.' }}</span>@if(!$readOnly)<button class="btn btn-light btn-sm" type="submit">Save answer</button>@endif</div>
</form>
<div class="question-footer">@if($position>1)<a class="btn btn-light" data-nav href="{{ route('attempts.show',[$attempt,'question'=>$position-1]) }}"><x-icon name="back"/> Previous</a>@else<span></span>@endif @if($position<$attempt->total_questions)<a class="btn btn-primary" data-nav href="{{ route('attempts.show',[$attempt,'question'=>$position+1]) }}">Next question <x-icon name="arrow"/></a>@else<span class="soft-badge">You have reached the last question.</span>@endif</div>
</section><aside class="attempt-aside"><section class="panel"><div data-region="attempt-summary">@include('attempts.summary')</div><div class="panel-callout"><x-icon name="check"/><p>Answers are saved individually. Stay connected; closing this window does not pause the timer.</p></div>
@if(!$readOnly)<form method="post" action="{{ route('attempts.submit',$attempt) }}" data-ajax data-requires-saves data-confirm="Submit your saved answers? Unanswered questions receive zero marks. You cannot edit answers after submission.">@csrf<x-errors/><button type="submit" class="btn btn-primary full-width">Finish &amp; submit <x-icon name="check"/></button></form>@endif</section></aside></div>
